title: Working Experience
logo: assets/images/Logo Github Photo.png
#descrition:
#sho_download: true
#menu:
 # - title: "FactResellersSales table"
  #  url: "https://aldoreyes84.ghttps://github.com/AldoReyes84/Data-Analisys_For-AdventureWorksDW2022_SQL_PowerBI_Python_Excel/tree/main#factresellerssales-tableithub.io/AldoReyes.github.io/"
  #- title: "FactInternetSales table"
   # url: "## FactInternetSales table"
  #- title: "FactFinance table"
   # url: "##FactFinance table"
  
theme: jekyll-theme-minimal
